/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['home'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/confirmations/answer/{confirmation_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['save_answer'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/confirmations/create': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['create'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/confirmations/get/{confirmation_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['get_confirmation'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['health'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerContent:
            | {
                  text: string;
                  /** @enum {string} */
                  type: 'free_text';
              }
            | {
                  selected_indexes: number[];
                  /** @enum {string} */
                  type: 'options';
              };
        AnswerFormat:
            | {
                  /** @enum {string} */
                  type: 'free_text';
              }
            | {
                  multiple: boolean;
                  options: string[];
                  /** @enum {string} */
                  type: 'options';
              };
        /** @description The structure stored in DB for answers */
        ConfirmationAnswer: {
            answer_content: components['schemas']['AnswerContent'];
        };
        ConfirmationAnswerWithDate: {
            answer: components['schemas']['ConfirmationAnswer'];
            /** Format: date-time */
            answered_at: string;
        };
        /** @description The structure stored in DB for question */
        ConfirmationQuestion: {
            answer_format: components['schemas']['AnswerFormat'];
            body?: string | null;
            method: components['schemas']['QuestionMethod'];
            subject: string;
        };
        CreateConfirmationRequest: {
            callback_url?: string | null;
            context?: unknown;
            question: components['schemas']['ConfirmationQuestion'];
        };
        CreateConfirmationResponse: {
            /** Format: uuid */
            confirmation_request_id: string;
        };
        GetConfirmationResponse: {
            maybe_answer?: null | components['schemas']['ConfirmationAnswerWithDate'];
        };
        QuestionMethod: {
            /** @enum {string} */
            type: 'push';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Home page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    save_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Confirmation UUID */
                confirmation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ConfirmationAnswer'];
            };
        };
        responses: {
            /** @description Answer saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Confirmation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already confirmed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CreateConfirmationRequest'];
            };
        };
        responses: {
            /** @description Confirmation created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['CreateConfirmationResponse'];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_confirmation: {
        parameters: {
            query: {
                long_poll: boolean;
            };
            header?: never;
            path: {
                /** @description Confirmation UUID */
                confirmation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirmation status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GetConfirmationResponse'];
                };
            };
            /** @description Wrong project key */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Confirmation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
