/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * backend
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const saveAnswerParams = zod.object({
    confirmation_id: zod.uuid().describe('Confirmation UUID')
});

export const saveAnswerBodyAnswerContentSelectedIndexesItemMin = 0;

export const saveAnswerBody = zod
    .object({
        answer_content: zod.union([
            zod.object({
                text: zod.string(),
                type: zod.enum(['free_text'])
            }),
            zod.object({
                selected_indexes: zod.array(
                    zod.number().min(saveAnswerBodyAnswerContentSelectedIndexesItemMin)
                ),
                type: zod.enum(['options'])
            })
        ])
    })
    .describe('The structure stored in DB for answers');

export const createBody = zod.object({
    callback_url: zod.string().nullish(),
    context: zod.unknown().optional(),
    question: zod
        .object({
            answer_format: zod.union([
                zod.object({
                    type: zod.enum(['free_text'])
                }),
                zod.object({
                    multiple: zod.boolean(),
                    options: zod.array(zod.string()),
                    type: zod.enum(['options'])
                })
            ]),
            body: zod.string().nullish(),
            method: zod.object({
                type: zod.enum(['push'])
            }),
            subject: zod.string()
        })
        .describe('The structure stored in DB for question')
});

export const createResponse = zod.object({
    confirmation_request_id: zod.uuid()
});

export const getConfirmationParams = zod.object({
    confirmation_id: zod.uuid().describe('Confirmation UUID')
});

export const getConfirmationQueryParams = zod.object({
    long_poll: zod.boolean()
});

export const getConfirmationResponseMaybeAnswerAnswerAnswerContentSelectedIndexesItemMin = 0;

export const getConfirmationResponse = zod.object({
    maybe_answer: zod
        .union([
            zod.null(),
            zod.object({
                answer: zod
                    .object({
                        answer_content: zod.union([
                            zod.object({
                                text: zod.string(),
                                type: zod.enum(['free_text'])
                            }),
                            zod.object({
                                selected_indexes: zod.array(
                                    zod
                                        .number()
                                        .min(
                                            getConfirmationResponseMaybeAnswerAnswerAnswerContentSelectedIndexesItemMin
                                        )
                                ),
                                type: zod.enum(['options'])
                            })
                        ])
                    })
                    .describe('The structure stored in DB for answers'),
                answered_at: zod.iso.datetime({})
            })
        ])
        .optional()
});
